### ISSUE TITLE
[TASK] Docker image

### ISSUE THREAD

**Issue by VladRodionov** [carrotdata/memcarrot#20]
Goals:

- Find minimum size for Linux which allows us to run server (must pass all tests, maven required)
- Use minimized JRE version (ticket will open)
- Allows to start image with a custom server's configuration

**Comment by kzheludkov** [comment]
Finally we stood up with bellsoft/liberica-openjre-alpine:21.0.4-9-aarch64 and bellsoft/liberica-openjre-alpine:21.0.4-9-x86-64
