### ISSUE TITLE
[BUG] memcarrot.sh does not accept custom config file location

### ISSUE THREAD

**Issue by VladRodionov** [carrotdata/memcarrot#78]
We should support passing custom config file location.

**Comment by kzheludkov** [comment]
memcarrot-docker-run.sh  updated to pass customized configuration 

memcarrot/bin/memcarrot-docker-run.sh -h
Usage: memcarrot-docker-run.sh [--image IMAGE] [--tag NAME] [--name CONTAINER] [--help]

   -i, --image docker id      Specify the image ID. Example: f277649686cb08687af03ca784afebc4e0c7a29f889ec438eefaf667f3ee1758
   -t, --tag                  Specify the tag of 0.14.2-arm64
   -n  --name                 Specify the container name. Example: memcarrot
   **-c  --config               Specify the custom config to use in Docker container**
   -h, --help                 Display this help message
