### ISSUE TITLE
[TASK] Fix  docker scripts to run properly on Linux

### ISSUE THREAD

**Issue by VladRodionov** [carrotdata/memcarrot#80]

**Comment by VladRodionov** [comment]
Specify bash shell to use.

**Comment by kzheludkov** [comment]
Updated to bash. However, it doesn't test on different platforms.

**Comment by VladRodionov** [comment]
?. It was resolved yesterday.

**Comment by VladRodionov** [comment]
😄

**Comment by kzheludkov** [comment]
oh, I just replaced ksh to bash. :(

**Comment by kzheludkov** [comment]
It is docker non-public repo

**Comment by VladRodionov** [comment]
Wrong project 😄 You need to open ticket in other repo, commit and resolve it.

**Comment by kzheludkov** [comment]
Oh, sorry, I saw it was under carrto-cache.
